
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const ScrapingControl = lazy(() => import("./pages/ScrapingControl.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/scraping-control", element: <UserGuard><ScrapingControl /></UserGuard>},
	{ path: "/scrapingcontrol", element: <UserGuard><ScrapingControl /></UserGuard>},

];
